[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "soamp"
version = "0.1.0"
description = "SMILES-based, organism-based AMP classification"
requires-python = ">=3.12"
dependencies = [
    "rdkit==2026.3.5",
    "pandas==3.0.5",
    "numpy==2.5.1",
    "requests==2.34.2",
    "qmap-benchmark==0.1.1",
    "p2smi==1.1.1",
    "ete4==4.4.0",
    "igraph==1.0.0",
    "leidenalg==0.12.0",
    "pyyaml==6.0.3",
    "pydantic==2.13.4",
    "torch==2.13.0",
    "scikit-learn==1.9.0",
    "python-dotenv==1.2.2",
    "transformers==5.16.1",
    "SmilesPE==0.0.3",
    "wandb==0.28.2",
]

[project.optional-dependencies]
dev = [
    "jupyter==1.1.1",
    "pytest==9.1.1",
    "matplotlib==3.11.1",
    "umap-learn==0.5.12",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
soamp = ["features/peptideclm/*.txt"]
